//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecoview_Normal {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Analis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Analis() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecoview_Normal.Analis", typeof(Analis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool Asred_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Asred.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=492,Y=134}.
        /// </summary>
        internal static System.Drawing.Point backgroundWorker1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("backgroundWorker1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=17,Y=134}.
        /// </summary>
        internal static System.Drawing.Point colorDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("colorDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool Column1_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Column1.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool Concetr_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Concetr.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=669,Y=95}.
        /// </summary>
        internal static System.Drawing.Point contextMenuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=393,Y=134}.
        /// </summary>
        internal static System.Drawing.Point dataSet1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("dataSet1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=136,Y=95}.
        /// </summary>
        internal static System.Drawing.Point imageList1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("imageList1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=138,Y=134}.
        /// </summary>
        internal static System.Drawing.Point menuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool NoCo_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NoCo.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool Obrazec_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Obrazec.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=253,Y=134}.
        /// </summary>
        internal static System.Drawing.Point openFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("openFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=824,Y=95}.
        /// </summary>
        internal static System.Drawing.Point printDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("printDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=17,Y=95}.
        /// </summary>
        internal static System.Drawing.Point printDialog2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("printDialog2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon printPreviewTable1_Icon {
            get {
                object obj = ResourceManager.GetObject("printPreviewTable1.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=246,Y=95}.
        /// </summary>
        internal static System.Drawing.Point printPreviewTable1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("printPreviewTable1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon printPreviewTable2_Icon {
            get {
                object obj = ResourceManager.GetObject("printPreviewTable2.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=401,Y=95}.
        /// </summary>
        internal static System.Drawing.Point printPreviewTable2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("printPreviewTable2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=1073,Y=56}.
        /// </summary>
        internal static System.Drawing.Point printTable1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("printTable1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=556,Y=95}.
        /// </summary>
        internal static System.Drawing.Point printTable2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("printTable2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=943,Y=95}.
        /// </summary>
        internal static System.Drawing.Point saveFileDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("saveFileDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=1079,Y=95}.
        /// </summary>
        internal static System.Drawing.Point timer1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("timer1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
